language: go
arch:
    - amd64
    - ppc64le

go:  tip
  
  #to Exclude failed test cases
matrix: 
   allow_failures:
    - go: 1.2
    - go: 1.3
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8

