name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.17
          - 1.13
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        if: ${{ matrix.go-version != '1.13' }}
      - name: Set up Staticcheck (Go v1.13)
        run: GO111MODULE=on go get -u honnef.co/go/tools/cmd/staticcheck@2021.1
        if: ${{ matrix.go-version == '1.13' }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vet
        run: go vet -v ./...
      - name: Staticcheck
        run: staticcheck ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v -cover ./...
